name: PHP tests
on: [push, pull_request]
jobs:

  header-stamp:
    name: Header stamp
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - run: composer install --prefer-dist
      - run: ./src2/bin/header-stamp --exclude=vendor,src2/vendor,node_modules --dry-run --display-report